---
- name: Pull and Run docker containers
  hosts: all
  tasks:
    - name: Pull Spring WebApp image
      docker_image:
        name: akshil007/webapp
        source: pull



    - name: Pull blockchain image
      docker_image:
        name: akshil007/blockchain_medical
        source: pull



    - name: Run WebApp container
      docker:
        name: WebApplication
        image: akshil007/webapp
        state: started



    - name: Run blockchain container
      docker:
        name: blockchainNode
        image: akshil007/blockchain_medical
        state: started