---
- name: Pull and Run docker containers
  hosts: all
  tasks:
    - name: Pull Spring WebApp image
      docker_image:
        name: akshil007/HealthCareApp
        source: pull



    - name: Pull blockchain image
      docker_image:
        name: akshil007/blockchain_medical
        source: pull



    - name: Run WebApp container
      docker_container:
        name: WebApplication
        image: akshil007/HealthCareApp
        state: started
        recreate: yes


    - name: Run blockchain container
      docker_container:
        name: blockchainNode
        image: akshil007/blockchain_medical
        state: started
        recreate: yes