---
- name: Pull and Run docker containers
  hosts: all
  tasks:
    - name: Remove mysql existing container
      docker_container:
        name: healthcare-db
        state: absent

    - name: Remove Spring WebApp existing container
      docker_container:
        name: healthcare-webapp
        state: absent

    - name: Remove blockchain existing container
      docker_container:
        name: healthcare-blockchain
        state: absent

    # - name: Remove image
    #   docker_image:
    #     state: absent
    #     name: registry.ansible.com/chouseknecht/sinatra
    #     tag: v1

    - name: Docker pull mysql
      docker_image:
        name: mysql:8.0.23
        source: pull


    - name: Remove Previously Created Docker Network
      docker_network:
        name: health_net
        state: absent
        force: yes


    - name: Create Docker New Network
      docker_network:
        name: health_net


    - name: Pull Spring WebApp image
      docker_image:
        name: akshil007/health_care_app
        source: pull


    - name: Pull blockchain image
      docker_image:
        name: akshil007/blockchain_medical
        source: pull


    - name: Create MYSQL container
      docker_container:
        name: healthcare-db
        image: mysql:8.0.23
        networks:
          - name: "health_net"
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: HealthCareData
        ports:
          - "8090:3306"

    - name: Run command if /path/to/database does not exist (without 'args')
      ansible.builtin.command: /usr/bin/make_database.sh db_user db_name creates=/path/to/database

    - name: Create Web Application container
      docker_container:
        name: healthcare-webapp
        image: akshil007/health_care_app
        networks:
          - name: "health_net"
        env:
          DATABASE_HOST: healthcare_host
        ports:
          - "8085:8083"


    # - name: Run WebApp container
    #   docker_container:
    #     name: healthcare-webapp
    #     image: akshil007/health_care_app
    #     state: started
    #     recreate: yes


    - name: Run blockchain container
      docker_container:
        name: healthcare-blockchain
        image: akshil007/blockchain_medical
        state: started
        recreate: yes